Repository MysteriousGreenBean/crystalforum, pull requests merged in 2024-08, with the labels that each got.

#2 building stylesheets on run, better handling of monitor events
  docker/monitor/monitor.ps1
  start-env.ps1
  website/handlestylesheetsandtemplates.php
Labels: enhancement

#5 Topic-view-user
  templates/4_crystallicum_dark_templates/postbit/postbit_classic.html
Labels: bug

#6 Update issue templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/dev.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: devops

#4 updating signature.js
  templates/4_crystallicum_dark_templates/postbit/postbit_classic.html
  website/jscripts/signature.js
  website/jscripts/sticky.js
Labels: bug
